import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";

import "./globals.css";

const league_spartan = League_Spartan({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dine Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${league_spartan.className} m-0 box-border p-0 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
